# Generated by Django 4.2.16 on 2024-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='user',
            name='capital',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='자본금'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
