# Generated by Django 4.2.16 on 2024-11-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
                ('deal_bas_r', models.FloatField()),
                ('bkpr', models.FloatField()),
                ('yy_efee_r', models.FloatField()),
                ('ten_dd_efee_r', models.FloatField()),
                ('kftc_bkpr', models.FloatField()),
                ('kftc_deal_bas_r', models.FloatField()),
            ],
        ),
    ]
