# Generated by Django 4.2.16 on 2024-11-19 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_exchangerate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
    ]
